OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Models/ErrorViewModel.cs
namespace NavigationAndRouting.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Models/LoginViewModel.cs
namespace NavigationAndRouting.Models
{
    public class LoginViewModel
    {
        public string userName { get; set; }
        public string password { get; set; }
    }
}

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Areas/Admin/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace NavigationAndRouting.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Areas/User/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace NavigationAndRouting.Areas.User.Controllers
{
    public class UserController : Controller
    {
        [Area("User")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NavigationAndRouting.Models;
using System.Diagnostics;

namespace NavigationAndRouting.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using NavigationAndRouting.Models;
using NuGet.Protocol.Plugins;

namespace NavigationAndRouting.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
      
       

        [HttpPost]
        public IActionResult Index(LoginViewModel login)
        {
            if (ModelState.IsValid)
            {
                if (login.userName == "user@gmail.com" && login.password == "12345678")
                {
                    return RedirectToAction("Index", "User", new { area = "User" });
                }
                else if (login.userName == "admin@gmail.com" && login.password == "12345678")
                {
                    return RedirectToAction("Index", "Admin", new { area = "Admin" });
                }
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Mvc;

namespace NavigationAndRouting.Controllers
{
    public class LogoutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Areas/Admin/Views/Admin/Index.cshtml
<h1>Admin View</h1>

<a asp-area="" asp-controller="Logout" asp-action="Index">Logout</a>

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NavigationAndRouting</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NavigationAndRouting.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NavigationAndRouting</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Admin" asp-action="Index">Admin</a>
                        </li>
                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NavigationAndRouting - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Areas/User/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NavigationAndRouting</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NavigationAndRouting.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NavigationAndRouting</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="User" asp-action="Index">User</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NavigationAndRouting - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Areas/User/Views/User/Index.cshtml
<h1>User Logged In</h1>

<a asp-area="" asp-controller="Logout" asp-action="Index">Logout</a>

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Views/Login/Index.cshtml
@model LoginViewModel

<h1>Login</h1>
<form method="post" asp-controller="Login" asp-action="Index">

  
  
 

<div>
        Username:  <input type="text" asp-for="userName"/>
</div>
    <br />
    <div>
        Password:  <input type="text" asp-for="password" />
    </div>


    <br/>

 

    <div>

     <button type="submit">Login</button>
    </div>

</form>

OneDrive/Desktop/CoreTraining/Copy of Assignments/NavigationAndRouting/NavigationAndRouting/Views/Logout/Index.cshtml
<h1>Logged out successfully.</h1>