OneDrive/Desktop/CoreTraining/TrainingAssignments/ViewComponentPartialViewAssignment/ViewComponentPartialViewAssignment/Models/CommentViewModel.cs
namespace ViewComponentPartialViewAssignment.Models
{
    public class CommentViewModel
    {
        public int id { get; set; }
        public int postId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string body { get; set; }
    }
}

OneDrive/Desktop/CoreTraining/TrainingAssignments/ViewComponentPartialViewAssignment/ViewComponentPartialViewAssignment/Models/ErrorViewModel.cs
namespace ViewComponentPartialViewAssignment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OneDrive/Desktop/CoreTraining/TrainingAssignments/ViewComponentPartialViewAssignment/ViewComponentPartialViewAssignment/Models/PostViewModel.cs
namespace ViewComponentPartialViewAssignment.Models
{
    public class PostViewModel
    {
        public int userId { get; set; }
        public string title { get; set; }

        public int id { get; set; }

        public string body { get; set; }
    }
}

OneDrive/Desktop/CoreTraining/TrainingAssignments/ViewComponentPartialViewAssignment/ViewComponentPartialViewAssignment/Components/CommentsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using ViewComponentPartialViewAssignment.Models;

namespace ViewComponentPartialViewAssignment.Components
{
    public class CommentsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(CommentViewModel comment)
        {

            return View("~/Views/Components/_Comments.cshtml" ,comment);

        }
    }
}

OneDrive/Desktop/CoreTraining/TrainingAssignments/ViewComponentPartialViewAssignment/ViewComponentPartialViewAssignment/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ViewComponentPartialViewAssignment.Models;

namespace ViewComponentPartialViewAssignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OneDrive/Desktop/CoreTraining/TrainingAssignments/ViewComponentPartialViewAssignment/ViewComponentPartialViewAssignment/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using ViewComponentPartialViewAssignment.Models;
using static System.Net.WebRequestMethods;

namespace ViewComponentPartialViewAssignment.Controllers
{
    public class PostController : Controller
    {
        public async Task<IActionResult> Index()
        {
            HttpClient client = new HttpClient();
           
            client.BaseAddress = new Uri("https://jsonplaceholder.typicode.com/");
            IEnumerable<PostViewModel> model = new List<PostViewModel>();
            var response = await client.GetAsync(client.BaseAddress + "posts");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsStringAsync();
                model = JsonSerializer.Deserialize<IEnumerable<PostViewModel>>(data);
            }

            PostViewModel post = model.FirstOrDefault();
        

            IEnumerable<CommentViewModel> modelComment = new List<CommentViewModel>();
            var responseComment = await client.GetAsync(client.BaseAddress + "comments");
            if (responseComment.IsSuccessStatusCode)
            {
                var dataComment = await responseComment.Content.ReadAsStringAsync();
                modelComment = JsonSerializer.Deserialize<IEnumerable<CommentViewModel>>(dataComment);
            }
            CommentViewModel comment = modelComment.FirstOrDefault(x=>x.postId == post.id);
            var tupleModel = new Tuple<PostViewModel,CommentViewModel>(post, comment);

            return View(tupleModel);
        }
    }
}

OneDrive/Desktop/CoreTraining/TrainingAssignments/ViewComponentPartialViewAssignment/ViewComponentPartialViewAssignment/Views/Post/Index.cshtml
@model Tuple<PostViewModel,CommentViewModel>

<h1> Post View </h1>

<p>Id: @Model.Item1.id </p>
<p>UserId: @Model.Item1.userId </p>
<p>Title: @Model.Item1.title </p>
<p>Body: @Model.Item1.body </p>

<br/>

@await Component.InvokeAsync("Comments",Model.Item2)

OneDrive/Desktop/CoreTraining/TrainingAssignments/ViewComponentPartialViewAssignment/ViewComponentPartialViewAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ViewComponentPartialViewAssignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ViewComponentPartialViewAssignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ViewComponentPartialViewAssignment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Post</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ViewComponentPartialViewAssignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>